root: true
extends:
- plugin:react/recommended
- plugin:prettier/recommended
plugins:
- react
- prettier
parser: babel-eslint
globals:
  __DEV__: true
  "$": true
rules:
  react/no-danger: 0
  no-useless-escape: 0
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
